# Generated by Django 5.0 on 2026-01-25 14:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("created_by", models.UUIDField(db_index=True)),
                ("title", models.CharField(max_length=255)),
                ("summary", models.CharField(blank=True, default="", max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("start_datetime", models.DateTimeField(db_index=True)),
                ("end_datetime", models.DateTimeField(db_index=True)),
                ("all_day", models.BooleanField(default=False)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("renewal", "Renewal"),
                            ("expiry", "Expiry"),
                            ("meeting", "Meeting"),
                        ],
                        default="meeting",
                        max_length=32,
                    ),
                ),
                (
                    "associated_contract_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "associated_contract_title",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "calendar_events",
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "created_by", "start_datetime"],
                        name="calendar_ev_tenant__517d13_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "created_by", "end_datetime"],
                        name="calendar_ev_tenant__7da475_idx",
                    ),
                ],
            },
        ),
    ]
