# Generated by Django 5.0 on 2026-01-19 12:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "contracts",
            "0002_contract_approval_chain_contract_approval_required_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SignNowCredential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "access_token",
                    models.TextField(help_text="Current OAuth access token"),
                ),
                (
                    "refresh_token",
                    models.TextField(
                        help_text="OAuth refresh token for renewing access"
                    ),
                ),
                (
                    "token_expires_at",
                    models.DateTimeField(help_text="When the access token expires"),
                ),
                (
                    "client_id",
                    models.CharField(
                        help_text="SignNow OAuth client ID", max_length=500
                    ),
                ),
                (
                    "client_secret",
                    models.CharField(
                        help_text="SignNow OAuth client secret", max_length=500
                    ),
                ),
                (
                    "account_name",
                    models.CharField(
                        help_text="Service account display name", max_length=255
                    ),
                ),
                (
                    "account_id",
                    models.CharField(
                        help_text="SignNow service account ID", max_length=255
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_refreshed_at",
                    models.DateTimeField(
                        blank=True, help_text="Last token refresh time", null=True
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "SignNow Credentials",
                "db_table": "signnow_credentials",
            },
        ),
        migrations.CreateModel(
            name="ESignatureContract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "signnow_document_id",
                    models.CharField(
                        db_index=True,
                        help_text="SignNow document ID",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent for Signature"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("declined", "Declined"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Current signing status",
                        max_length=20,
                    ),
                ),
                (
                    "signing_order",
                    models.CharField(
                        choices=[
                            ("sequential", "Sequential"),
                            ("parallel", "Parallel"),
                        ],
                        default="parallel",
                        help_text="Sequential or parallel signing",
                        max_length=20,
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, help_text="When sent for signature", null=True
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When all signers completed", null=True
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="Signing deadline", null=True
                    ),
                ),
                (
                    "last_status_check_at",
                    models.DateTimeField(
                        blank=True, help_text="Last status polling time", null=True
                    ),
                ),
                (
                    "original_r2_key",
                    models.CharField(
                        help_text="Original contract PDF in R2", max_length=500
                    ),
                ),
                (
                    "executed_r2_key",
                    models.CharField(
                        blank=True,
                        help_text="Signed contract PDF in R2",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contract",
                    models.OneToOneField(
                        help_text="Associated CLM contract",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="esignature_contract",
                        to="contracts.contract",
                    ),
                ),
            ],
            options={
                "db_table": "esignature_contracts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Signer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(help_text="Signer email address", max_length=254),
                ),
                (
                    "name",
                    models.CharField(help_text="Signer full name", max_length=255),
                ),
                (
                    "signing_order",
                    models.IntegerField(
                        help_text="Order in signing sequence (1-based)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "Invited"),
                            ("viewed", "Viewed"),
                            ("in_progress", "In Progress"),
                            ("signed", "Signed"),
                            ("declined", "Declined"),
                        ],
                        db_index=True,
                        default="invited",
                        help_text="Current signing status",
                        max_length=20,
                    ),
                ),
                (
                    "has_signed",
                    models.BooleanField(
                        default=False, help_text="Whether signer completed"
                    ),
                ),
                (
                    "signed_at",
                    models.DateTimeField(
                        blank=True, help_text="When signer completed", null=True
                    ),
                ),
                (
                    "signing_url",
                    models.TextField(
                        blank=True, help_text="Embedded signing URL", null=True
                    ),
                ),
                (
                    "signing_url_expires_at",
                    models.DateTimeField(
                        blank=True, help_text="URL expiration (24h)", null=True
                    ),
                ),
                (
                    "declined_reason",
                    models.TextField(
                        blank=True, help_text="Reason if declined", null=True
                    ),
                ),
                (
                    "invited_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When invitation sent"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "esignature_contract",
                    models.ForeignKey(
                        help_text="Associated e-signature contract",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signers",
                        to="contracts.esignaturecontract",
                    ),
                ),
            ],
            options={
                "db_table": "signers",
                "ordering": ["signing_order", "email"],
            },
        ),
        migrations.CreateModel(
            name="SigningAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("invite_sent", "Invitation Sent"),
                            ("document_viewed", "Document Viewed"),
                            ("signing_started", "Signing Started"),
                            ("signing_completed", "Signing Completed"),
                            ("signing_declined", "Signing Declined"),
                            ("status_checked", "Status Checked"),
                            ("document_downloaded", "Document Downloaded"),
                        ],
                        db_index=True,
                        help_text="Event type",
                        max_length=50,
                    ),
                ),
                ("message", models.TextField(help_text="Event description")),
                (
                    "old_status",
                    models.CharField(
                        blank=True,
                        help_text="Previous status",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        blank=True, help_text="New status", max_length=20, null=True
                    ),
                ),
                (
                    "signnow_response",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Full SignNow API response",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "esignature_contract",
                    models.ForeignKey(
                        help_text="Associated e-signature contract",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="contracts.esignaturecontract",
                    ),
                ),
                (
                    "signer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated signer (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="contracts.signer",
                    ),
                ),
            ],
            options={
                "db_table": "signing_audit_logs",
                "ordering": ["-created_at"],
                "permissions": [
                    ("view_signing_audit_log", "Can view signing audit logs")
                ],
            },
        ),
        migrations.AddIndex(
            model_name="esignaturecontract",
            index=models.Index(
                fields=["signnow_document_id"], name="esignature__signnow_ec610d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="esignaturecontract",
            index=models.Index(fields=["status"], name="esignature__status_35b189_idx"),
        ),
        migrations.AddIndex(
            model_name="esignaturecontract",
            index=models.Index(
                fields=["contract", "status"], name="esignature__contrac_dfac26_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="signer",
            index=models.Index(
                fields=["esignature_contract", "status"],
                name="signers_esignat_99ccd8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="signer",
            index=models.Index(fields=["email"], name="signers_email_6b103d_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="signer",
            unique_together={("esignature_contract", "email")},
        ),
        migrations.AddIndex(
            model_name="signingauditlog",
            index=models.Index(
                fields=["esignature_contract", "created_at"],
                name="signing_aud_esignat_8517c5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="signingauditlog",
            index=models.Index(
                fields=["event", "created_at"], name="signing_aud_event_8d3ae9_idx"
            ),
        ),
    ]
