# Generated by Django 5.0 on 2026-01-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0003_signnowcredential_esignaturecontract_signer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="clauses",
            field=models.JSONField(
                default=list, help_text="List of contract clauses and constraints"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="signed",
            field=models.JSONField(
                default=dict,
                help_text="Signature information from SignNow with signer names",
            ),
        ),
    ]
