# Generated by Django 5.0 on 2026-01-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0004_contract_clauses_contract_signed"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="signed_pdf",
            field=models.BinaryField(
                blank=True,
                help_text="Signed PDF from SignNow with user signature",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="signnow_document_id",
            field=models.CharField(
                blank=True, help_text="SignNow document ID", max_length=255, null=True
            ),
        ),
    ]
