# Generated by Django 5.0 on 2026-01-24 11:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0005_contract_signed_pdf_contract_signnow_document_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clause",
            name="alternatives",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="clause",
            name="clause_id",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="clause",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="clause",
            name="contract_type",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="clause",
            name="created_by",
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name="clause",
            name="is_mandatory",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="clause",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="clause",
            name="source_template",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="clause",
            name="source_template_version",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="clause",
            name="tags",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="clause",
            name="tenant_id",
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name="clause",
            name="version",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="contracttemplate",
            name="business_rules",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="contracttemplate",
            name="contract_type",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="contracttemplate",
            name="created_by",
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name="contracttemplate",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contracttemplate",
            name="mandatory_clauses",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="contracttemplate",
            name="merge_fields",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="contracttemplate",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="contracttemplate",
            name="r2_key",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="contracttemplate",
            name="tenant_id",
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name="contracttemplate",
            name="version",
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name="ContractEditingSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("user_id", models.UUIDField()),
                ("template_id", models.UUIDField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "form_data",
                    models.JSONField(default=dict, help_text="User-filled form data"),
                ),
                (
                    "selected_clause_ids",
                    models.JSONField(
                        default=list, help_text="User-selected clause IDs"
                    ),
                ),
                (
                    "custom_clauses",
                    models.JSONField(
                        default=dict, help_text="Custom clause content by user"
                    ),
                ),
                (
                    "constraints_config",
                    models.JSONField(
                        default=dict, help_text="Constraint/version definitions"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_saved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "contract_editing_sessions",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "user_id"],
                        name="contract_ed_tenant__107cb2_idx",
                    ),
                    models.Index(
                        fields=["status", "updated_at"],
                        name="contract_ed_status_eeae45_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ContractEditingTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "base_template_id",
                    models.UUIDField(help_text="ID of base ContractTemplate"),
                ),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(default="general", max_length=100)),
                ("contract_type", models.CharField(max_length=100)),
                (
                    "form_fields",
                    models.JSONField(
                        default=dict,
                        help_text='Form field definitions like:\n        {\n            "party_a_name": {\n                "label": "Your Company Name",\n                "type": "text",\n                "required": true,\n                "placeholder": "Enter your company name",\n                "validation": {"min_length": 2, "max_length": 255}\n            },\n            "party_b_name": {\n                "label": "Counterparty Name",\n                "type": "text",\n                "required": true\n            },\n            "contract_value": {\n                "label": "Contract Value (USD)",\n                "type": "number",\n                "required": true,\n                "min": 0,\n                "max": 999999999\n            }\n        }',
                    ),
                ),
                (
                    "default_values",
                    models.JSONField(
                        default=dict, help_text="Default values for form fields"
                    ),
                ),
                (
                    "mandatory_clauses",
                    models.JSONField(
                        default=list, help_text="List of mandatory clause IDs"
                    ),
                ),
                (
                    "optional_clauses",
                    models.JSONField(
                        default=list, help_text="List of optional clause IDs"
                    ),
                ),
                (
                    "clause_order",
                    models.JSONField(default=list, help_text="Suggested clause order"),
                ),
                (
                    "constraint_templates",
                    models.JSONField(
                        default=dict,
                        help_text='Predefined constraints users can apply:\n        {\n            "payment_terms": {\n                "label": "Payment Terms",\n                "options": ["Net 30", "Net 60", "Net 90", "Immediate"],\n                "default": "Net 30"\n            },\n            "jurisdiction": {\n                "label": "Governing Jurisdiction",\n                "options": ["California", "New York", "Delaware", "Federal"],\n                "default": "California"\n            }\n        }',
                    ),
                ),
                (
                    "contract_content_template",
                    models.TextField(
                        help_text="Base contract template with {{placeholders}} for form fields"
                    ),
                ),
                (
                    "styling_config",
                    models.JSONField(
                        default=dict,
                        help_text="Professional styling for generated contracts",
                    ),
                ),
                (
                    "preview_sample",
                    models.TextField(
                        blank=True, help_text="Sample preview of contract"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_by", models.UUIDField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "contract_editing_templates",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "is_active"],
                        name="contract_ed_tenant__ad528a_idx",
                    ),
                    models.Index(
                        fields=["contract_type"], name="contract_ed_contrac_99d897_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ContractEditingStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("template_selection", "Template Selected"),
                            ("form_fill", "Form Field Filled"),
                            ("clause_selection", "Clause Selected"),
                            ("clause_removal", "Clause Removed"),
                            ("clause_customization", "Clause Customized"),
                            ("constraint_definition", "Constraint Defined"),
                            ("preview_generated", "Preview Generated"),
                            ("field_edited", "Field Edited After Preview"),
                            ("saved", "Draft Saved"),
                        ],
                        max_length=30,
                    ),
                ),
                ("step_data", models.JSONField(help_text="Data for this step")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="contracts.contracteditingsession",
                    ),
                ),
            ],
            options={
                "db_table": "contract_editing_steps",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["session", "timestamp"],
                        name="contract_ed_session_cb6d11_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ContractEdits",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "edit_type",
                    models.CharField(
                        choices=[
                            ("form_field", "Form Field Edited"),
                            ("clause_added", "Clause Added"),
                            ("clause_removed", "Clause Removed"),
                            ("clause_content_edited", "Clause Content Edited"),
                            ("constraint_added", "Constraint Added"),
                            ("constraint_modified", "Constraint Modified"),
                        ],
                        max_length=30,
                    ),
                ),
                ("field_name", models.CharField(blank=True, max_length=255)),
                ("old_value", models.JSONField(blank=True, null=True)),
                ("new_value", models.JSONField(blank=True, null=True)),
                (
                    "edit_reason",
                    models.TextField(
                        blank=True, help_text="Why the user made this edit"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edits",
                        to="contracts.contracteditingsession",
                    ),
                ),
            ],
            options={
                "db_table": "contract_edits",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["session", "timestamp"],
                        name="contract_ed_session_fe3edb_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ContractFieldValidationRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("field_name", models.CharField(max_length=255)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("regex", "Regular Expression"),
                            ("min_value", "Minimum Value"),
                            ("max_value", "Maximum Value"),
                            ("length", "String Length"),
                            ("custom", "Custom Validation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("rule_value", models.JSONField(help_text="Rule configuration")),
                ("error_message", models.CharField(max_length=500)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_validations",
                        to="contracts.contracteditingtemplate",
                    ),
                ),
            ],
            options={
                "db_table": "contract_field_validation_rules",
                "unique_together": {("template", "field_name", "rule_type")},
            },
        ),
        migrations.CreateModel(
            name="ContractPreview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "preview_html",
                    models.TextField(help_text="HTML preview of contract"),
                ),
                (
                    "preview_text",
                    models.TextField(help_text="Plain text version of contract"),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "form_data_snapshot",
                    models.JSONField(
                        help_text="Snapshot of form data used for preview"
                    ),
                ),
                (
                    "clauses_snapshot",
                    models.JSONField(help_text="Snapshot of selected clauses"),
                ),
                (
                    "constraints_snapshot",
                    models.JSONField(help_text="Snapshot of constraints used"),
                ),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preview",
                        to="contracts.contracteditingsession",
                    ),
                ),
            ],
            options={
                "db_table": "contract_previews",
                "indexes": [
                    models.Index(
                        fields=["session"], name="contract_pr_session_1d396e_idx"
                    )
                ],
            },
        ),
    ]
