# Generated by Django 5.0 on 2026-02-03 00:00

import uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0006_alter_clause_alternatives_alter_clause_clause_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FirmaSignatureContract",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("firma_document_id", models.CharField(max_length=255, unique=True, db_index=True, help_text="Firma document/envelope ID")),
                ("status", models.CharField(max_length=20, default="draft", db_index=True, choices=[("draft", "Draft"), ("sent", "Sent for Signature"), ("in_progress", "In Progress"), ("completed", "Completed"), ("declined", "Declined"), ("failed", "Failed")],)),
                ("signing_order", models.CharField(max_length=20, default="sequential", choices=[("sequential", "Sequential"), ("parallel", "Parallel")],)),
                ("sent_at", models.DateTimeField(null=True, blank=True)),
                ("completed_at", models.DateTimeField(null=True, blank=True)),
                ("expires_at", models.DateTimeField(null=True, blank=True)),
                ("last_status_check_at", models.DateTimeField(null=True, blank=True)),
                ("original_r2_key", models.CharField(max_length=500, help_text="Original contract PDF in R2")),
                ("executed_r2_key", models.CharField(max_length=500, null=True, blank=True, help_text="Signed contract PDF in R2")),
                ("signing_request_data", models.JSONField(default=dict, null=True, blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contract",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="firma_signature_contract",
                        help_text="Associated CLM contract",
                        to="contracts.contract",
                    ),
                ),
            ],
            options={
                "db_table": "firma_signature_contracts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FirmaSigner",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(max_length=255)),
                ("signing_order", models.IntegerField(help_text="Order in signing sequence (1-based)")),
                ("status", models.CharField(max_length=20, default="invited", db_index=True, choices=[("invited", "Invited"), ("viewed", "Viewed"), ("in_progress", "In Progress"), ("signed", "Signed"), ("declined", "Declined")],)),
                ("has_signed", models.BooleanField(default=False)),
                ("signed_at", models.DateTimeField(null=True, blank=True)),
                ("signing_url", models.TextField(null=True, blank=True)),
                ("signing_url_expires_at", models.DateTimeField(null=True, blank=True)),
                ("declined_reason", models.TextField(null=True, blank=True)),
                ("invited_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "firma_signature_contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signers",
                        to="contracts.firmasignaturecontract",
                    ),
                ),
            ],
            options={
                "db_table": "firma_signers",
                "ordering": ["signing_order", "email"],
                "unique_together": {("firma_signature_contract", "email")},
            },
        ),
        migrations.CreateModel(
            name="FirmaSigningAuditLog",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("event", models.CharField(max_length=50, db_index=True, choices=[("upload", "Document Uploaded"), ("invite_sent", "Invitation Sent"), ("status_checked", "Status Checked"), ("document_downloaded", "Document Downloaded"), ("error", "Error")],)),
                ("message", models.TextField()),
                ("old_status", models.CharField(max_length=20, null=True, blank=True)),
                ("new_status", models.CharField(max_length=20, null=True, blank=True)),
                ("firma_response", models.JSONField(default=dict, null=True, blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "firma_signature_contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="contracts.firmasignaturecontract",
                    ),
                ),
                (
                    "signer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.SET_NULL,
                        null=True,
                        blank=True,
                        related_name="audit_logs",
                        to="contracts.firmasigner",
                    ),
                ),
            ],
            options={
                "db_table": "firma_signing_audit_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="firmasignaturecontract",
            index=models.Index(fields=["firma_document_id"], name="firma_sc_docid_idx"),
        ),
        migrations.AddIndex(
            model_name="firmasignaturecontract",
            index=models.Index(fields=["status"], name="firma_sc_status_idx"),
        ),
        migrations.AddIndex(
            model_name="firmasignaturecontract",
            index=models.Index(fields=["contract", "status"], name="firma_sc_contract_status_idx"),
        ),
        migrations.AddIndex(
            model_name="firmasigner",
            index=models.Index(fields=["firma_signature_contract", "status"], name="firma_signer_sc_status_idx"),
        ),
        migrations.AddIndex(
            model_name="firmasigner",
            index=models.Index(fields=["email"], name="firma_signer_email_idx"),
        ),
    ]
